server:
  port: 8080

spring:
  application:
    name: rococo-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:9000'
grpc:
  client:
    grpcDataClient:
      max-inbound-message-size: 10485760
      address: "static://localhost:8093"
      negotiationType: PLAINTEXT

    grpcUserdataPublicClient:
      address: "static://localhost:8094"
      negotiationType: PLAINTEXT
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

rococo-front:
  base-uri: 'http://localhost:3000'
