server:
  port: 9000
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: 30m
      cookie:
        name: JSESSIONID
        max-age: 1800
      tracking-modes: cookie

spring:
  application:
    name: rococo-auth
  mvc:
    log-request-details: true
  session:
    timeout: 30m
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
            token-settings:
              access-token-time-to-live: 30m
              authorization-code-time-to-live: 30m
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rococo-auth
    locations: classpath:db/migration/rococo-auth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-auth?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              redirect-uris:
                - 'http://localhost:3000/authorized'
              post-logout-redirect-uris:
                - 'http://localhost:3000/logout'

grpc:
  client:
    grpcUserdataCreateUserClient:
      address: 'static://localhost:8094'
      negotiationType: PLAINTEXT

rococo-front:
  base-uri: 'http://localhost:3000'

rococo-auth:
  base-uri: 'http://localhost:9000'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:mysql://rococo-all-db:3306/rococo-auth?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              redirect-uris:
                - 'http://frontend.rococo.dc/authorized'
              post-logout-redirect-uris:
                - 'http://frontend.rococo.dc/logout'

grpc:
  client:
    grpcUserdataCreateUserClient:
      address: 'static://rococo-userdata:8094'
      negotiationType: PLAINTEXT

rococo-front:
  base-uri: 'http://frontend.rococo.dc'

rococo-auth:
  base-uri: 'http://auth.rococo.dc:9000'